# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Publish GitHub Release

on:
  push:
    branches:
      - devops/release

jobs:
  publish-github:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: powernukkit-releases # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Remove the custom suffix from the version
      run: sed -i 's@-CUSTOM</version>@</version>@' pom.xml
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Adjust the release repository url
      run: sed -i 's@https://oss.sonatype.org/service/local/staging/deploy/maven2/@https://maven.pkg.github.com/PowerNukkit/PowerNukkit@' pom.xml
    
    - name: Publish to GitHub Packages Apache Maven
      run: mvn -B deploy -Dgpg.skip=true -DskipTests=false -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
